# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eestell <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/06 21:30:05 by eestell           #+#    #+#              #
#    Updated: 2019/09/13 18:33:14 by eestell          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
OBJ = ft_display_file.o
CFILE = ft_display_file.c

all: 
	gcc -c $(CFILE)
	gcc -Wall -Wextra -Werror -o $(NAME) $(CFILE)
clean:
	rm -f $(OBJ)
fclean: clean
	rm -f $(NAME)
